services:
  aluno:
    build:
      context: .
      dockerfile: ./infra/Dockerfile
      args:
        SETUP_SCRIPT: setup_aluno.sh
    container_name: aluno
    networks:
      - lab-network
    tty: true
    stdin_open: true
    volumes:
      - ./exploits-safe/exploit.sh:/root/exploit.sh:ro

  professor:
    build:
      context: .
      dockerfile: ./infra/Dockerfile
      args:
        SETUP_SCRIPT: setup_professor.sh
    container_name: professor
    ports:
      - "2021:21"   # host 2021 -> container 21 (FTP)
      - "2222:22"   # host 2222 -> container 22 (SSH)
    networks:
      - lab-network
    tty: true
    stdin_open: true
    volumes:
      - ./infra:/root/infra:ro
      - ./exploits-safe:/tmp/exploits:ro

networks:
  lab-network:
    driver: bridge

